-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.drivers
(
    driver_id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    license_number character varying(50) COLLATE pg_catalog."default" NOT NULL,
    rating numeric(2, 1) DEFAULT 5.0,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT drivers_pkey PRIMARY KEY (driver_id),
    CONSTRAINT drivers_license_number_key UNIQUE (license_number),
    CONSTRAINT drivers_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.locations
(
    location_id serial NOT NULL,
    latitude numeric(9, 6) NOT NULL,
    longitude numeric(9, 6) NOT NULL,
    address text COLLATE pg_catalog."default",
    CONSTRAINT locations_pkey PRIMARY KEY (location_id)
);

CREATE TABLE IF NOT EXISTS public.payments
(
    payment_id serial NOT NULL,
    ride_id integer NOT NULL,
    amount numeric(10, 2) NOT NULL,
    payment_method character varying(50) COLLATE pg_catalog."default",
    payment_status payment_status DEFAULT 'pending'::payment_status,
    paid_at timestamp without time zone,
    CONSTRAINT payments_pkey PRIMARY KEY (payment_id),
    CONSTRAINT payments_ride_id_key UNIQUE (ride_id)
);

CREATE TABLE IF NOT EXISTS public.ratings
(
    rating_id serial NOT NULL,
    ride_id integer NOT NULL,
    rated_by_user integer,
    rated_by_driver integer,
    rating_value integer,
    comment text COLLATE pg_catalog."default",
    CONSTRAINT ratings_pkey PRIMARY KEY (rating_id),
    CONSTRAINT ratings_ride_id_key UNIQUE (ride_id)
);

CREATE TABLE IF NOT EXISTS public.rides
(
    ride_id serial NOT NULL,
    user_id integer NOT NULL,
    driver_id integer,
    pickup_location_id integer NOT NULL,
    drop_location_id integer NOT NULL,
    fare numeric(10, 2),
    surge_multiplier numeric(3, 2) DEFAULT 1.0,
    status ride_status DEFAULT 'requested'::ride_status,
    requested_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    started_at timestamp without time zone,
    ended_at timestamp without time zone,
    CONSTRAINT rides_pkey PRIMARY KEY (ride_id)
);

CREATE TABLE IF NOT EXISTS public.surge_pricing
(
    surge_id serial NOT NULL,
    location_id integer NOT NULL,
    multiplier numeric(3, 2) NOT NULL,
    start_time timestamp without time zone,
    end_time timestamp without time zone,
    CONSTRAINT surge_pricing_pkey PRIMARY KEY (surge_id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    full_name character varying(100) COLLATE pg_catalog."default" NOT NULL,
    email character varying(150) COLLATE pg_catalog."default" NOT NULL,
    phone character varying(15) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT users_email_key UNIQUE (email),
    CONSTRAINT users_phone_key UNIQUE (phone)
);

CREATE TABLE IF NOT EXISTS public.vehicles
(
    vehicle_id serial NOT NULL,
    driver_id integer,
    model character varying(100) COLLATE pg_catalog."default",
    plate_number character varying(20) COLLATE pg_catalog."default" NOT NULL,
    vehicle_type character varying(50) COLLATE pg_catalog."default",
    CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id),
    CONSTRAINT vehicles_driver_id_key UNIQUE (driver_id),
    CONSTRAINT vehicles_plate_number_key UNIQUE (plate_number)
);

ALTER TABLE IF EXISTS public.payments
    ADD CONSTRAINT payments_ride_id_fkey FOREIGN KEY (ride_id)
    REFERENCES public.rides (ride_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS payments_ride_id_key
    ON public.payments(ride_id);


ALTER TABLE IF EXISTS public.ratings
    ADD CONSTRAINT ratings_ride_id_fkey FOREIGN KEY (ride_id)
    REFERENCES public.rides (ride_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS ratings_ride_id_key
    ON public.ratings(ride_id);


ALTER TABLE IF EXISTS public.rides
    ADD CONSTRAINT rides_driver_id_fkey FOREIGN KEY (driver_id)
    REFERENCES public.drivers (driver_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rides
    ADD CONSTRAINT rides_drop_location_id_fkey FOREIGN KEY (drop_location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rides
    ADD CONSTRAINT rides_pickup_location_id_fkey FOREIGN KEY (pickup_location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.rides
    ADD CONSTRAINT rides_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.surge_pricing
    ADD CONSTRAINT surge_pricing_location_id_fkey FOREIGN KEY (location_id)
    REFERENCES public.locations (location_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.vehicles
    ADD CONSTRAINT vehicles_driver_id_fkey FOREIGN KEY (driver_id)
    REFERENCES public.drivers (driver_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS vehicles_driver_id_key
    ON public.vehicles(driver_id);

END;